pipeline {
    agent {
        docker {
            image 'ruby'
            args '--network rocklov-network'
        }
    }

    stages {
        stage('Build') {
            steps{
                sh 'cd web && bundle install'
            }
        }
        stage('Testing') {
            steps {
                sh 'cd web && rake test'
            }
        }
        stage('UAT') {
            steps {
                echo 'Aguardando testes de aceitação.'
                input message: 'Publicar?'
            }
        }
        stage('prod') {
            steps {
                echo 'WebApp para produção.'
            }
        }
    }
    post {
        always {
            echo 'TODO'
        }
    }
}